export const projects = [
  {
    title: 'My Portfolio',
    description: "Using React, and Next js to showcase my talents, what I've been working on, and who I am",
      image: '/images/portfolio.png',
      tags: ['React', 'Next', 'Javascript'],
    source: '',
    visit: 'https://github.com/jrcliff/react-next-portfolio',
    id: 0,
  },
  {
    title: 'ChatterCliff',
    description:"",
    image: '/images/ChatterCliff.png',
    tags: ['React', 'JavaScript', 'Ruby/Rails'],
    source: 'https://youtu.be/0y5rEDt69tc',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Compass',
    description: "",
      image: '/images/Compass.png',
      tags: ['Javascript', 'Ruby/Rails'],
    source: 'https://youtu.be/gvFHcA2PAR8',
    visit: 'https://github.com/jrcliff/compass-app-frontend',
    id: 2,
  },
  {
    title: 'GamerBook',
    description: "",
    image: '/images/GamerBook.png',
    tags: ['React', 'Ruby/Rails'],
    source: 'https://youtu.be/l5mHDsj3Ut0',
    visit: 'https://github.com/jrcliff/phase4-frontend',
    id: 3,
  },
  {
    title: '',
    description: '',
    image: '',
    tags: [],
    source: '',
    visit: '',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];